"""Style Reference (style_reference) service package.

PR-1 scope: schema 落地 only. 仅导出枚举 / 错误体系 / 仓储 / cleanup。
业务编排(extract / inject / validate)在后续 PR 中分别落地。

参见 plans/style-reference-v1-1-fancy-shannon.md 与
《风格参考模块重构执行手册 v1.1》§4 / §14。
"""

from __future__ import annotations

from novel_system.services.style_reference.dimensions import (
    LAYER_TO_SUB_DIMS,
    Layer,
    SubDimension,
)
from novel_system.services.style_reference.errors import (
    BannedAdjectiveError,
    DuplicateBookError,
    EmptyBookError,
    EvidenceShortError,
    EvidenceSpanError,
    LLMRequiredError,
    StyleReferenceError,
)
from novel_system.services.style_reference.extractors import (
    BaseExtractor,
    ExtractionRetryPolicy,
    ExtractionRunResult,
    LanguageExtractor,
    NarrativeExtractor,
    SceneExtractor,
    ThemeExtractor,
)
from novel_system.services.style_reference.ingest import IngestResult, IngestService, assess_input_size
from novel_system.services.style_reference.injection import InjectionService
from novel_system.services.style_reference.materialization import (
    MaterializationService,
    MaterializeResult,
)
from novel_system.services.style_reference.preview import PreviewService
from novel_system.services.style_reference.profile_synthesizer import ProfileSynthesizer
from novel_system.services.style_reference.run_orchestrator import RunOrchestrator, RunResult
from novel_system.services.style_reference.validation import (
    ValidationOrchestrator,
    check_forbidden_local,
    check_forbidden_semantic,
    check_plagiarism,
    check_quantitative,
    check_semantic,
    run_sync_validate,
)
from novel_system.services.style_reference.metrics import (
    METRIC_NAMES,
    MetricName,
    MetricsEngine,
    ParagraphRecord,
)
from novel_system.services.style_reference.segmentation import (
    ParagraphClassification,
    SegmentationLLMError,
    SegmentationResult,
    classify_paragraphs,
)
from novel_system.services.style_reference.schemas import (
    AnchorKind,
    BannedTermScope,
    BindingScope,
    BindingStatus,
    BookStatus,
    CloudPolicy,
    ExtractionEvidenceInput,
    ExtractionFindingInput,
    ExtractionOutput,
    ExtractionPurpose,
    ExtractionStatus,
    FindingKind,
    FindingStatus,
    InjectionStrategy,
    InputAssessmentLevel,
    ParagraphType,
    ProfileStatus,
    RunPhase,
    RunStatus,
    StyleReferenceBannedTermRow,
    StyleReferenceBookRow,
    StyleReferenceEvidenceRow,
    StyleReferenceExtractionRow,
    StyleReferenceFindingRow,
    StyleReferenceInjectionBindingRow,
    StyleReferenceParagraphRow,
    StyleReferenceProfileRow,
    StyleReferenceQuoteRow,
    StyleReferenceRunRow,
    StyleReferenceValidationReportRow,
    SupplementEvidenceOutput,
    TaskType,
    ValidationMode,
    ValidationTargetKind,
    ValidationVerdict,
    ProfileSubDimensionSummary,
    SynthesizedProfile,
    PlagiarismHit,
    PlagiarismReport,
    ForbiddenHit,
    ValidationReport,
    PreviewGeneratedSample,
    PreviewSampleResult,
    InjectionPreviewRequest,
    InjectionPreviewResponse,
    QuantitativeReportItem,
    SemanticReportItem,
    SystemPromptFragments,
    ValidateRequest,
    ValidateResponse,
)

__all__ = [
    "Layer",
    "SubDimension",
    "LAYER_TO_SUB_DIMS",
    "ParagraphType",
    "FindingKind",
    "AnchorKind",
    "BookStatus",
    "ExtractionStatus",
    "ExtractionPurpose",
    "FindingStatus",
    "RunStatus",
    "RunPhase",
    "ProfileStatus",
    "BindingScope",
    "BindingStatus",
    "InjectionStrategy",
    "TaskType",
    "ValidationVerdict",
    "ValidationMode",
    "ValidationTargetKind",
    "BannedTermScope",
    "InputAssessmentLevel",
    "CloudPolicy",
    "StyleReferenceError",
    "BannedAdjectiveError",
    "EvidenceShortError",
    "EvidenceSpanError",
    "DuplicateBookError",
    "EmptyBookError",
    "LLMRequiredError",
    "ExtractionEvidenceInput",
    "ExtractionFindingInput",
    "ExtractionOutput",
    "SupplementEvidenceOutput",
    "ProfileSubDimensionSummary",
    "SynthesizedProfile",
    "PlagiarismHit",
    "PlagiarismReport",
    "ForbiddenHit",
    "ValidationReport",
    "PreviewGeneratedSample",
    "PreviewSampleResult",
    "InjectionPreviewRequest",
    "InjectionPreviewResponse",
    "QuantitativeReportItem",
    "SemanticReportItem",
    "SystemPromptFragments",
    "ValidateRequest",
    "ValidateResponse",
    "IngestService",
    "IngestResult",
    "assess_input_size",
    "InjectionService",
    "BaseExtractor",
    "LanguageExtractor",
    "NarrativeExtractor",
    "SceneExtractor",
    "ThemeExtractor",
    "ExtractionRetryPolicy",
    "ExtractionRunResult",
    "RunOrchestrator",
    "RunResult",
    "ProfileSynthesizer",
    "MaterializationService",
    "MaterializeResult",
    "PreviewService",
    "ValidationOrchestrator",
    "run_sync_validate",
    "check_plagiarism",
    "check_forbidden_local",
    "check_quantitative",
    "check_semantic",
    "check_forbidden_semantic",
    "MetricsEngine",
    "ParagraphRecord",
    "MetricName",
    "METRIC_NAMES",
    "classify_paragraphs",
    "ParagraphClassification",
    "SegmentationResult",
    "SegmentationLLMError",
    "StyleReferenceBookRow",
    "StyleReferenceParagraphRow",
    "StyleReferenceExtractionRow",
    "StyleReferenceQuoteRow",
    "StyleReferenceEvidenceRow",
    "StyleReferenceFindingRow",
    "StyleReferenceRunRow",
    "StyleReferenceProfileRow",
    "StyleReferenceInjectionBindingRow",
    "StyleReferenceValidationReportRow",
    "StyleReferenceBannedTermRow",
]
